### ISSUE TITLE
2.0 Release meta issue

### ISSUE THREAD

**Issue by vojtechkral** [vojtechkral/bard#1]
2.0 checklist:

- [x] LaTeX processing refactor
  - [x] Auto LaTeX lookup
  - [x] Define PDF format
  - [x] `tex` config option
  - Provide local overriding → postponed to post-2.0
  - [x] Replace post-processing with a script option
  - [x] Built-in Tectonic on Windows (cf. #13)
- [x] `bard.toml` v2 update, versioning
- [x] Hbs math helper #14
- [x] Tests & CI updates
- [x] `bard.toml` migration guide
- [x] #2
